name: üß™ Testes e SonarCloud

on:
  workflow_run:
    workflows: [ "üèóÔ∏è Build" ]  # Executa ap√≥s o build
    types:
      - completed

jobs:
  test_sonar:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'


      - name: Rodar testes
        run: mvn test

      - name: An√°lise SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify sonar:sonar \
          -Dsonar.projectKey=mariomendonca_learning-pipelines \
          -Dsonar.organization=mariomendonca \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
